### ISSUE TITLE
php artisan migrate has an error

### ISSUE THREAD

**Issue by emilas44** [hoadv/employee-mgmt-laravel5.4-adminlte#1]
On initial migrate I get an error complaining about "can't add foreign key"

```[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL  
  : alter table `employees` add constraint `employees_city_id_foreign` foreig  
  n key (`city_id`) references `city` (`id`))                                  
                                                                               

                                                                          
  [PDOException]                                                          
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint

**Comment by emilas44** [comment]
You have made a big mistake...You can't assign a foreign key from a table that doesn't exist!

**Comment by maufel** [comment]
I fixed the error. 
How I can share the solutions ?

**Comment by emilas44** [comment]
Push the changes you have made to your github project

**Comment by maufel** [comment]
do it

2017-06-25 9:52 GMT+02:00 emilas44 <notifications@github.com>:

**Comment by emilas44** [comment]
I can't push to your git repository! It works though. You need to push it!

**Comment by maufel** [comment]
How to do i t ?

Il 25/giu/2017 1:15 PM, "emilas44" <notifications@github.com> ha scritto:

**Comment by emilas44** [comment]
How did you push it at the first place?

**Comment by emilas44** [comment]
Or maybe this is not your code? That whole application?

**Comment by maufel** [comment]
I fix only some problemi. It's noto mine

Il 25/giu/2017 6:49 PM, "emilas44" <notifications@github.com> ha scritto:

**Comment by emilas44** [comment]
OK, i get it this is a forked repository... you just pulled it to your git hub profile.... am I right?

**Comment by maufel** [comment]
try this :
https://github.com/maufel/employee-mgmt-laravel5.4-adminlte

best regards

2017-06-25 21:09 GMT+02:00 emilas44 <notifications@github.com>:

**Comment by hoadv** [comment]
Hello @emilas44 , have you see my video? I did this step by step without error.

**Comment by emilas44** [comment]
No, I haven't seen the video...can you post the link here please.

**Comment by hoadv** [comment]
https://www.youtube.com/watch?v=Jbt5bEgv_QM

**Comment by emilas44** [comment]
OK very nice, thank you
