### ISSUE TITLE
Missing vendor Folder

### ISSUE THREAD

**Issue by vyrussbeatz** [hoadv/employee-mgmt-laravel5.4-adminlte#20]
The vendor is missing in this repository leading to error:

_

> PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /home/vyruss/click/employee-mgmt-laravel5.4-adminlte/bootstrap/app.php:14
> Stack trace:
> #0 /home/vyruss/click/employee-mgmt-laravel5.4-adminlte/artisan(18): require_once()
> #1 {main}
>   thrown in /home/vyruss/click/employee-mgmt-laravel5.4-adminlte/bootstrap/app.php on line 14

_

I pasted a vendor folder into the offline repo. Still, Another error was prompted;

**_

> In excel.php line 182:
>                                           
>   Class 'PHPExcel_Shared_Font' not found

_**

**Comment by hoadv** [comment]
Run "composer update" to generate it, follow all steps at https://www.youtube.com/watch?v=Jbt5bEgv_QM
