### ISSUE TITLE
Issue when running the migrate

### ISSUE THREAD

**Issue by tons613** [hoadv/employee-mgmt-laravel5.4-adminlte#4]
When i run the migrate command I got the error below. Any idea on how to fix it?

[Illuminate\Database\QueryException]                                                                                                                                              
  SQLSTATE[HY000]: General error: 1005 Can't create table `employee_db`.`#sql-123c_53` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `employees` add cons  
  traint `employees_city_id_foreign` foreign key (`city_id`) references `city` (`id`))

**Comment by bodoschmidt** [comment]
I have the same Porblem

**Comment by AnjanRaoCh** [comment]
Getting the same problem here

**Comment by Manuchekhr** [comment]
i have these problems too

**Comment by frogetii** [comment]
I have the same problem too. Anyone out there?

**Comment by hoadv** [comment]
Refer to hot fix 1 and 2: 
 https://www.youtube.com/watch?v=bDmmKOdgIeY
https://www.youtube.com/watch?v=cEdQvdYLuSg
