### ISSUE TITLE
Artisan Migrate Issues

### ISSUE THREAD

**Issue by sickcity** [hoadv/employee-mgmt-laravel5.4-adminlte#5]
when i try to execute php artisan migrate it gives me these errors below:
 [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from information_schema.tables where table_schema = employees_db and table_name = migrations)

  [PDOException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

pls help

**Comment by rojonunoo** [comment]
yeah have the same issue anyone with the fix to this problem?

**Comment by hoadv** [comment]
Please follow step by step of video at https://www.youtube.com/watch?v=Jbt5bEgv_QM
